### ISSUE TITLE
Ainda dá usar essa versão antiga?

### ISSUE THREAD

**Issue by maxleon52** [italoiz/unform-community-packages#10]
Boa tarde Italo, fiquei muito interessado nessa lib, e gostaria de saber se ainda dá pra usar a mesma, visto que a Rockeseat atualizou o unForm para a versão 2.0, dai eu não sei como a sua vai se comportar no momento que eu instalar o unForm.

**Comment by italoiz** [comment]
Hi @maxleon52 

I did not test with version 2.0 of Unform, however, in the coming weeks a new summer will be coming out that will support version 2.0 of Unform.

**Comment by italoiz** [comment]
Hi @maxleon52 

I launched a new version, see: https://www.npmjs.com/package/unform-material-ui
