### ISSUE TITLE
InputLabel not shrinking when onFocus

### ISSUE THREAD

**Issue by vanialadev** [italoiz/unform-community-packages#26]
![image](https://user-images.githubusercontent.com/22610714/85474430-0cea8880-b58b-11ea-9387-465e5b0ea664.png)

The <InpuLabel /> of the <TextFiel /> component is not shrinking when the component onFocus.

` InputLabelProps={{
                  shrink: true,
                }}` 
dont work

**Comment by italoiz** [comment]
Hi, @vanialadev can you provide an example and what the version of the library are you using?

**Comment by vanialadev** [comment]
```jsx
<Grid item lg={3} sm={6} xl={3} xs={12}>
  <TextField
    label="Nome"
    name="nome"
    variant="outlined"
    type="text"
    error
    InputLabelProps={{
      shrink: true,
    }}
  />
</Grid>
<Grid item lg={3} sm={6} xl={3} xs={12}>
  <TextField
    label="CPF"
    name="cpf"
    variant="outlined"
    type="text"
    error
    placeholder="CPFF"
    InputLabelProps={{
      shrink: true,
    }}
  />
</Grid>
```

![image](https://user-images.githubusercontent.com/22610714/85476318-6dc79000-b58e-11ea-9f6d-5ae299461be4.png)
The label should`ve appear at the top because I forced it up at the code, but it doesn't happen

![image](https://user-images.githubusercontent.com/22610714/85476655-2beb1980-b58f-11ea-92bc-e5cd66dbaaef.png)
The label was supposed to go to the top when I click at the box, but it only goes up when I start to type 
![image](https://user-images.githubusercontent.com/22610714/85476723-47562480-b58f-11ea-98eb-5944a820a2b6.png)

version:     "unform-material-ui": "^1.0.1",

**Comment by eliton-algoll** [comment]
I also have this problem, any solution?

**Comment by eliton-algoll** [comment]
I also have this problem, any solution?

**Comment by italoiz** [comment]
@eliton-algoll Yes, I resolved this problem, but I doing tests to ensure the quality of code. I will send a new version in this week :wink:
