### ISSUE TITLE
Input Mask

### ISSUE THREAD

**Issue by guitexa** [italoiz/unform-community-packages#36]
Hi everyone!

Whats the best way to set a mask on this `<TextField />` ?

I'm trying to implement `react-input-mask` as recommended on http://unform.dev but I can't get the value of the Input, as yo can see on this SandBox below.

https://codesandbox.io/s/unform-with-react-input-mask-kygkd

I don't want to use `onChange` to prevent lots of renders.

Is there another way to do that?

Thanks 🙏🏼

**Comment by italoiz** [comment]
@guitexa You should be pass props to `InputMask` component. Try the below example:

```jsx
  const InputWithMask = useCallback((props): JSX.Element => {
    return (
      <InputMask
        {...props} // <-- Put this line in your code.
        mask="(99) 9 9999-9999"
        maskChar={null}
        style={{ border: "none" }}
      />
    );
  }, []);
```

**Comment by guitexa** [comment]
> 
> 
> @guitexa You should be pass props to `InputMask` component. Try the below example:
> 
> ```js-jsx
>   const InputWithMask = useCallback((props): JSX.Element => {
>     return (
>       <InputMask
>         {...props} // <-- Put this line in your code.
>         mask="(99) 9 9999-9999"
>         maskChar={null}
>         style={{ border: "none" }}
>       />
>     );
>   }, []);
> ```

I appreciate your help but it's not work either =/
Thanks 🙏🏼

**Comment by guitexa** [comment]
@italoiz very nice, your suggestion helped a lot, as you can see on SandBox below, I imported props interface from `react-input-mask` and it works fine.

https://codesandbox.io/s/unform-with-react-input-mask-kygkd

```jsx
import InputMask, { Props as InputProps } from "react-input-mask";
```

```jsx
const InputWithMask = useCallback((props: InputProps): JSX.Element => {
    return (
      <InputMask
        {...props}
        mask="(99) 9 9999-9999"
        maskChar={null}
        style={{ border: "none" }}
      />
    );
  }, []);
```

Thank you so much 🙏🏼
