### ISSUE TITLE
Uncontroled Checkbox setData not work's

### ISSUE THREAD

**Issue by jairokoning** [italoiz/unform-community-packages#37]
Hello @italoiz 

When I try to set checked a uncontrolled Checkbox in `formRef.current.setData` nothing is happening, it seems that this is not working. But the Textfield is working normal.

Code on [CodeSandbox](https://codesandbox.io/s/material-demo-forked-g73yv?file=/demo.tsx)

```
import React, { useEffect, useRef } from "react";
import { Form } from "@unform/web";
import { FormHandles } from "@unform/core";
import { Checkbox, TextField } from "unform-material-ui";

export default function CheckboxLabels() {
  const formRef = useRef<FormHandles>(null);

  function handleSubmit(data) {
    formRef.current.setData({
      name: !data.terms,
      terms: !data.terms
    });
    console.log(data);
  }

  useEffect(() => {
    formRef.current.setData({
      name: "false",
      terms: true
    });

    formRef.current.setFieldValue("terms", true);
  }, []);

  return (
    <Form ref={formRef} onSubmit={handleSubmit}>
      <div>
        <Checkbox name="terms" />
      </div>

      <div>
        <TextField name="name" />
      </div>

      <button type="submit">Send</button>
    </Form>
  );
}

```

![checbox](https://user-images.githubusercontent.com/29260158/94326439-465fd500-ff7a-11ea-9b8d-5e14973f6238.gif)

**Comment by jairokoning** [comment]
@italoiz Is the reported problem a bug or is there something wrong with the code? Because the property is changed to true/false but visually in the checkbox nothing happens.

**Comment by italoiz** [comment]
Hi @jairokoning, it looks like a bug, I will take it easy this week.

**Comment by jairokoning** [comment]
@italoiz any fix for the bug? I needed a solution with some urgency, because I am using the component in a professional project in the company where I work.

**Comment by italoiz** [comment]
@jairokoning I cannot guarantee but in the next few days, I will be releasing a new version. Thank you!
